cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
      folder:
        image: ${S3_IMAGE_FOLDER}
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  servlet:
    session:
      tracking-modes: cookie

app:
  default-profile-image-url: ${DEFAULT_PROFILE_IMAGE_URL}